"""Add trips relation on incident model

Revision ID: 0f5dbb107e69
Revises: 479dd2e2263a
Create Date: 2025-09-13 08:28:03.783730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5dbb107e69'
down_revision: Union[str, None] = '479dd2e2263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'trip_id')
    # ### end Alembic commands ###