"""Add update trip model and direction column

Revision ID: 1aa6a8d91985
Revises: 40dc595f340a
Create Date: 2025-09-12 04:12:34.567890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa6a8d91985'
down_revision: Union[str, None] = '40dc595f340a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the Enum type here to use in both upgrade and downgrade
tripdirection_enum = sa.Enum('TO_SCHOOL', 'FROM_SCHOOL', name='tripdirection')


def upgrade() -> None:
    # ### Corrected Migration Steps ###
    
    # 1. Create the new ENUM type
    tripdirection_enum.create(op.get_bind())
    
    # 2. Add the column, but make it nullable for now
    op.add_column('trips', sa.Column('direction', tripdirection_enum, nullable=True))
    
    # 3. Update all existing rows to have a default value.
    #    We'll assume existing trips were 'TO_SCHOOL'.
    op.execute("UPDATE trips SET direction = 'TO_SCHOOL' WHERE direction IS NULL")
    
    # 4. Now that all rows have a value, alter the column to be NOT NULL.
    op.alter_column('trips', 'direction', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the column that uses the ENUM
    op.drop_column('trips', 'direction')
    
    # Then, drop the ENUM type itself
    tripdirection_enum.drop(op.get_bind())