"""Add trips relation on incident model

Revision ID: 2a8281afd8d0
Revises: 0f5dbb107e69
Create Date: 2025-09-13 08:30:39.767801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8281afd8d0'
down_revision: Union[str, None] = '0f5dbb107e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###