"""Add driver and bus to incidents

Revision ID: 354ed9e20fe6
Revises: 2513813ebf25
Create Date: 2025-09-10 12:43:17.091910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354ed9e20fe6'
down_revision: Union[str, None] = '889f05f4b7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('bus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'users', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'buses', ['bus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'bus_id')
    op.drop_column('incidents', 'driver_id')
    # ### end Alembic commands ###