"""Add update route to incidents

Revision ID: 40dc595f340a
Revises: 83fa8c91bd83
Create Date: 2025-09-11 13:04:23.846697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dc595f340a'
down_revision: Union[str, None] = '83fa8c91bd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('incidents_trip_id_fkey', 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'trip_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incidents_trip_id_fkey', 'incidents', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###