"""Add trips relation on incident model

Revision ID: 479dd2e2263a
Revises: 1aa6a8d91985
Create Date: 2025-09-13 08:24:12.441527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479dd2e2263a'
down_revision: Union[str, None] = '1aa6a8d91985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###