"""Add relationship between trip,bus,route to incidents

Revision ID: 83fa8c91bd83
Revises: 354ed9e20fe6
Create Date: 2025-09-11 12:58:21.865263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fa8c91bd83'
down_revision: Union[str, None] = '354ed9e20fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'trip_id')
    # ### end Alembic commands ###