"""add_lat_long_to_school_and_student

Revision ID: a5e0254b95b4
Revises: 982f1834241c
Create Date: 2026-02-02 10:04:57.163942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e0254b95b4'
down_revision: Union[str, None] = '982f1834241c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'longitude')
    op.drop_column('students', 'latitude')
    op.drop_column('students', 'address')
    op.drop_column('schools', 'longitude')
    op.drop_column('schools', 'latitude')
    # ### end Alembic commands ###